// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Movies.Filter {
    public enum GetSortQueryParameterType {
        [EnumMember(Value = "score")]
        Score,
        [EnumMember(Value = "firstAired")]
        FirstAired,
        [EnumMember(Value = "name")]
        Name,
    }
}
