// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace ApiSdk.Models {
    /// <summary>
    /// translation extended record
    /// </summary>
    public class TranslationExtended : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alias property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Alias { get; set; }
#nullable restore
#else
        public List<string> Alias { get; set; }
#endif
        /// <summary>The nameTranslations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Translation>? NameTranslations { get; set; }
#nullable restore
#else
        public List<Translation> NameTranslations { get; set; }
#endif
        /// <summary>The overviewTranslations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Translation>? OverviewTranslations { get; set; }
#nullable restore
#else
        public List<Translation> OverviewTranslations { get; set; }
#endif
        /// <summary>
        /// Instantiates a new TranslationExtended and sets the default values.
        /// </summary>
        public TranslationExtended() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static TranslationExtended CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new TranslationExtended();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"alias", n => { Alias = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"nameTranslations", n => { NameTranslations = n.GetCollectionOfObjectValues<Translation>(Translation.CreateFromDiscriminatorValue)?.ToList(); } },
                {"overviewTranslations", n => { OverviewTranslations = n.GetCollectionOfObjectValues<Translation>(Translation.CreateFromDiscriminatorValue)?.ToList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("alias", Alias);
            writer.WriteCollectionOfObjectValues<Translation>("nameTranslations", NameTranslations);
            writer.WriteCollectionOfObjectValues<Translation>("overviewTranslations", OverviewTranslations);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
