// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Updates
{
    #pragma warning disable CS1591
    public enum GetActionQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "delete")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
        [EnumMember(Value = "update")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
    }
}
