// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Updates {
    public enum GetActionQueryParameterType {
        [EnumMember(Value = "delete")]
        Delete,
        [EnumMember(Value = "update")]
        Update,
    }
}
