// <auto-generated/>
using ApiSdk.Seasons.Item.Extended;
using ApiSdk.Seasons.Item.Translations;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ApiSdk.Seasons.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \seasons\{id}
    /// </summary>
    public class SeasonsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The extended property</summary>
        public ApiSdk.Seasons.Item.Extended.ExtendedRequestBuilder Extended
        {
            get => new ApiSdk.Seasons.Item.Extended.ExtendedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The translations property</summary>
        public ApiSdk.Seasons.Item.Translations.TranslationsRequestBuilder Translations
        {
            get => new ApiSdk.Seasons.Item.Translations.TranslationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiSdk.Seasons.Item.SeasonsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SeasonsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/seasons/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiSdk.Seasons.Item.SeasonsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SeasonsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/seasons/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Returns season base record
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Seasons.Item.SeasonsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<ApiSdk.Seasons.Item.SeasonsGetResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<ApiSdk.Seasons.Item.SeasonsGetResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<ApiSdk.Seasons.Item.SeasonsGetResponse>(requestInfo, ApiSdk.Seasons.Item.SeasonsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns season base record
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="ApiSdk.Seasons.Item.SeasonsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public ApiSdk.Seasons.Item.SeasonsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new ApiSdk.Seasons.Item.SeasonsItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
