// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Series.Filter
{
    #pragma warning disable CS1591
    public enum GetSortTypeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "asc")]
        #pragma warning disable CS1591
        Asc,
        #pragma warning restore CS1591
        [EnumMember(Value = "desc")]
        #pragma warning disable CS1591
        Desc,
        #pragma warning restore CS1591
    }
}
