// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Series.Filter {
    public enum GetSortTypeQueryParameterType {
        [EnumMember(Value = "asc")]
        Asc,
        [EnumMember(Value = "desc")]
        Desc,
    }
}
