// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.Series.Item.Extended {
    public enum GetMetaQueryParameterType {
        [EnumMember(Value = "translations")]
        Translations,
        [EnumMember(Value = "episodes")]
        Episodes,
    }
}
