// <auto-generated/>
using ApiSdk.Lists.Slug.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace ApiSdk.Lists.Slug
{
    /// <summary>
    /// Builds and executes requests for operations under \lists\slug
    /// </summary>
    public class SlugRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ApiSdk.lists.slug.item collection</summary>
        /// <param name="position">slug</param>
        /// <returns>A <see cref="ApiSdk.Lists.Slug.Item.WithSlugItemRequestBuilder"/></returns>
        public ApiSdk.Lists.Slug.Item.WithSlugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("slug", position);
                return new ApiSdk.Lists.Slug.Item.WithSlugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiSdk.Lists.Slug.SlugRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SlugRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/lists/slug", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="ApiSdk.Lists.Slug.SlugRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SlugRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/lists/slug", rawUrl)
        {
        }
    }
}
