// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.People.Item.Extended
{
    #pragma warning disable CS1591
    public enum GetMetaQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "translations")]
        #pragma warning disable CS1591
        Translations,
        #pragma warning restore CS1591
    }
}
