// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace ApiSdk.People.Item.Extended {
    public enum GetMetaQueryParameterType {
        [EnumMember(Value = "translations")]
        Translations,
    }
}
